const myArray2 = [1, "Bogdan", true, 4, 5];
const myArray = myArray2;
console.log(myArray);
console.log(myArray2);
myArray2[3] = "Pesho";
console.log(myArray);
console.log(myArray2);
myArray[6] = "Gosho";
console.log(myArray);
console.log(myArray2);